# Generated by Django 4.2.10 on 2024-05-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_attributevalue_productattribute_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productlineattributevalue",
            old_name="atrribute_value",
            new_name="attribute_value",
        ),
        migrations.AlterUniqueTogether(
            name="productlineattributevalue",
            unique_together={("attribute_value", "product_line")},
        ),
    ]
