# Generated by Django 4.2.10 on 2024-05-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_product_product_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="productline",
            name="shop_produc_sku_535859_idx",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="available",
            new_name="active",
        ),
        migrations.RenameField(
            model_name="productline",
            old_name="available",
            new_name="active",
        ),
        migrations.AddField(
            model_name="category",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=235, unique=True),
        ),
        migrations.AddIndex(
            model_name="productline",
            index=models.Index(
                fields=["sku", "active"], name="shop_produc_sku_2ad1fa_idx"
            ),
        ),
    ]
