# Generated by Django 4.2.10 on 2024-05-27 16:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_remove_productline_shop_produc_sku_535859_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.AddField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["uuid"], name="shop_produc_uuid_c5199e_idx"),
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
    ]
