# Generated by Django 4.2.10 on 2024-05-27 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_remove_product_brand_product_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productline",
            name="weight",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="productline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_line",
                to="shop.product",
            ),
        ),
    ]
